 name: Publish 🚀

 on:
  workflow_dispatch:
  push:
    branches:
    - main

 env:
        AZURE_WEBAPP_NAME: deploying-app
        key-vault-uri: ${{ secrets.KEY_VAULT_URI }} 

 jobs:
   publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup .NET
        uses: actions/setup-dotnet@v3
        with:
           dotnet-version: '6.0.X'

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

     # - name: Install AZURE ClI
      #  run:  |
       #   sudo apt-get update
        #  sudo apt-get install azure cli

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

           
      
      - name: Authenticate with Azure
        run: 
           az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
     

      - name: Fetch keys from Azure Key Vault
        run: |
         export KEY_1=$(az keyvault secret show --name KEY_NAME --vault-name KEY_VAULT_NAME --query value -o tsv)

      - name: Create environment-specific manifest
        run: echo "key1:$KEY_1" > manifest.yml
        
           
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}  # Replace with your Azure App Service name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }} 
          key-vault-uri: ${{ secrets.KEY_VAULT_URI }}
         
    
